

CREATE TABLE URLS (
  HASH VARCHAR PRIMARY KEY,
  CREATED TIMESTAMP NULL,
  EXPIRATION_DATE TIMESTAMP NULL,
  ORIGINAL_URL VARCHAR NOT NULL,
  USER_ID BIGSERIAL NOT NULL
);

CREATE TABLE USERS (
  ID BIGSERIAL PRIMARY KEY,
  USER_NAME VARCHAR NOT NULL UNIQUE,
  FIRST_NAME VARCHAR NOT NULL,
  LAST_NAME VARCHAR NOT NULL,
  EMAIL VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL,
  PHONE VARCHAR NOT NULL
);
